## Creating Numpy Arrays

In [1]:
import numpy as np

In [2]:
list1 = [1,2,3]
x = np.array(list1)

In [3]:
x

array([1, 2, 3])

### Multidimensional Arrays

In [51]:
y = np.array([[4,5,6], [7,8,9]])
y

array([[4, 5, 6],
       [7, 8, 9]])

In [52]:
y.shape

(2, 3)

In [122]:
g = np.arange(0, 310, 6)
g

array([  0,   6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72,
        78,  84,  90,  96, 102, 108, 114, 120, 126, 132, 138, 144, 150,
       156, 162, 168, 174, 180, 186, 192, 198, 204, 210, 216, 222, 228,
       234, 240, 246, 252, 258, 264, 270, 276, 282, 288, 294, 300, 306])

In [123]:
g = np.arange(52) ** 2 # values till 52 squares
g

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601], dtype=int32)

In [124]:
g.size # made columns and rows which are multiples of 52

52

In [125]:
g.reshape(4,13)

array([[   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
         121,  144],
       [ 169,  196,  225,  256,  289,  324,  361,  400,  441,  484,  529,
         576,  625],
       [ 676,  729,  784,  841,  900,  961, 1024, 1089, 1156, 1225, 1296,
        1369, 1444],
       [1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401,
        2500, 2601]], dtype=int32)

In [56]:
k = np.linspace(0, 9, 20) # specify start and stop index, and the amount of numbers you want in between that range
k

array([0.        , 0.47368421, 0.94736842, 1.42105263, 1.89473684,
       2.36842105, 2.84210526, 3.31578947, 3.78947368, 4.26315789,
       4.73684211, 5.21052632, 5.68421053, 6.15789474, 6.63157895,
       7.10526316, 7.57894737, 8.05263158, 8.52631579, 9.        ])

In [57]:
k.resize(5, 4)
k

array([[0.        , 0.47368421, 0.94736842, 1.42105263],
       [1.89473684, 2.36842105, 2.84210526, 3.31578947],
       [3.78947368, 4.26315789, 4.73684211, 5.21052632],
       [5.68421053, 6.15789474, 6.63157895, 7.10526316],
       [7.57894737, 8.05263158, 8.52631579, 9.        ]])

In [58]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [59]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [60]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
y = np.append(y, [[3,3,3]], axis = 0) # append new row to y to make size 9

In [66]:
np.diag(y)

array([4, 8, 3])

In [67]:
np.diag(x)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [69]:
np.array([6,2,3] * 3)

array([6, 2, 3, 6, 2, 3, 6, 2, 3])

In [71]:
np.repeat([6,2,3], 3)

array([6, 6, 6, 2, 2, 2, 3, 3, 3])

In [74]:
p = np.ones([2,5], int); p

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [76]:
np.vstack([p, 3* p])

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [77]:
np.hstack([p, 3* p])

array([[1, 1, 1, 1, 1, 3, 3, 3, 3, 3],
       [1, 1, 1, 1, 1, 3, 3, 3, 3, 3]])

In [78]:
x

array([1, 2, 3])

In [88]:
y = np.array([3,4,5])
y

array([3, 4, 5])

In [89]:
x+y

array([4, 6, 8])

In [90]:
x*y

array([ 3,  8, 15])

In [91]:
x ** 3

array([ 1,  8, 27], dtype=int32)

In [92]:
y.dot(x)

26

In [94]:
z = np.array([y,y**2])
z

array([[ 3,  4,  5],
       [ 9, 16, 25]])

In [96]:
z.shape

(2, 3)

In [98]:
z.size

6

In [103]:
z.T.shape # transpose of z matrix

(3, 2)

In [104]:
z.dtype

dtype('int32')

In [108]:
z = z.astype('f')
z.dtype

dtype('float32')

## Numpy Math Functions

In [109]:
a = np.array([3,2,6,-1,-192,55])

In [110]:
a.sum()

-127

In [111]:
a.max()

55

In [112]:
a.min()

-192

In [115]:
a.mean()

-21.166666666666668

In [116]:
a.std()

78.79385903877423

In [118]:
a.argmax() #index of the maximum value

5

In [119]:
a.argmin() # index of the minimum value

4

## Indexing and Slicing

In [130]:
e = np.arange(13) ** 2
e

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

In [142]:
e[2] ,e[-1], e[0:7:] # start:end:step-size (can avoid specifying the step-size)

(4, 144, array([ 0,  1,  4,  9, 16, 25, 36], dtype=int32))

In [143]:
e[1:5]

array([ 1,  4,  9, 16], dtype=int32)

In [144]:
e[-4::] # slice of the last 4 elements of the array

array([ 81, 100, 121, 144], dtype=int32)

In [145]:
e[-5::-2]

array([64, 36, 16,  4,  0], dtype=int32)

In [146]:
e[-5:-2:]

array([ 64,  81, 100], dtype=int32)

In [181]:
r = np.arange(49)
r.resize(7,7)
r

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [182]:
r[4,5]

33

In [183]:
r[4, 3:7] # fourth row and 3 to 7 columns

array([31, 32, 33, 34])

In [184]:
r[:2, :-1] # first two rows, all the columns except the last

array([[ 0,  1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11, 12]])

In [185]:
r[::, ::2] # Selecting every second element on each row

array([[ 0,  2,  4,  6],
       [ 7,  9, 11, 13],
       [14, 16, 18, 20],
       [21, 23, 25, 27],
       [28, 30, 32, 34],
       [35, 37, 39, 41],
       [42, 44, 46, 48]])

In [186]:
r[r>30]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48])

In [187]:
r[r>30] = 30 # capping the values at 30
r

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30]])

In [188]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 7,  8,  9],
       [14, 15, 16]])

In [189]:
r2[:] = 0 # changes the values in r as well because it is assigned to r
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [190]:
r

array([[ 0,  0,  0,  3,  4,  5,  6],
       [ 0,  0,  0, 10, 11, 12, 13],
       [ 0,  0,  0, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30]])

In [191]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5,  6],
       [ 0,  0,  0, 10, 11, 12, 13],
       [ 0,  0,  0, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30]])

In [192]:
r_copy[r_copy > 25] = 25
print(r_copy)
print() # new line
print(r) # r will remain unchanged as we made a shallow copy of r

[[ 0  0  0  3  4  5  6]
 [ 0  0  0 10 11 12 13]
 [ 0  0  0 17 18 19 20]
 [21 22 23 24 25 25 25]
 [25 25 25 25 25 25 25]
 [25 25 25 25 25 25 25]
 [25 25 25 25 25 25 25]]

[[ 0  0  0  3  4  5  6]
 [ 0  0  0 10 11 12 13]
 [ 0  0  0 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 30 30 30 30]
 [30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30]]


In [193]:
r_copy

array([[ 0,  0,  0,  3,  4,  5,  6],
       [ 0,  0,  0, 10, 11, 12, 13],
       [ 0,  0,  0, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25]])

In [195]:
r_copy[:, 0]

array([ 0,  0,  0, 21, 25, 25, 25])

## Iterating Over Arrays

In [204]:
test = np.random.randint(0,20, (4,5))
test

array([[ 5,  0,  4,  2,  6],
       [ 9,  0, 11, 10, 15],
       [13,  0, 13, 16, 13],
       [ 2,  8, 15, 14, 11]])

In [205]:
for row in test:
    print(row)

[5 0 4 2 6]
[ 9  0 11 10 15]
[13  0 13 16 13]
[ 2  8 15 14 11]


In [206]:
for i in range(len(test)):
    print(test[i])

[5 0 4 2 6]
[ 9  0 11 10 15]
[13  0 13 16 13]
[ 2  8 15 14 11]


In [207]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [5 0 4 2 6]
row 1 is [ 9  0 11 10 15]
row 2 is [13  0 13 16 13]
row 3 is [ 2  8 15 14 11]


In [214]:
x = ['apple', 'orange', 'grape']
y = enumerate(x)
print(type(y))
for i in y:
    print(i)

<class 'enumerate'>
(0, 'apple')
(1, 'orange')
(2, 'grape')


In [208]:
test2 = test ** 2
test2

array([[ 25,   0,  16,   4,  36],
       [ 81,   0, 121, 100, 225],
       [169,   0, 169, 256, 169],
       [  4,  64, 225, 196, 121]], dtype=int32)

In [215]:
for i,j in zip(test, test2):
    print(i, '+' , j, '=', i+j)

[5 0 4 2 6] + [25  0 16  4 36] = [30  0 20  6 42]
[ 9  0 11 10 15] + [ 81   0 121 100 225] = [ 90   0 132 110 240]
[13  0 13 16 13] + [169   0 169 256 169] = [182   0 182 272 182]
[ 2  8 15 14 11] + [  4  64 225 196 121] = [  6  72 240 210 132]


In [218]:
['a','b','c'] + [1,2,3] # a list can have multiple different types in it

['a', 'b', 'c', 1, 2, 3]

In [221]:
my_function = lambda x : x*2
type(my_function)

function

In [222]:
my_arr = np.arange(36)
my_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [237]:
my_arr.resize(6,6)
my_arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [232]:
my_arr.reshape(36)[::7] # reshape to 36 elements in 1 row and select every 7th element

array([ 0,  7, 14, 21, 28, 35])

In [238]:
my_arr[2:4,2:4] # get the middle 4 elements

array([[14, 15],
       [20, 21]])